# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea6446570949ae9f88bd1087b08132a0f3cc6315fd01f2ea2961b348b5719c7da5878b19b807a704a0a8ba8491cb763f8a81f148c991be015baa69304fdcdef7

test:
  secret_key_base: 0efb12ca9120b13e77a0546a7789150f372d4b732b8b569e975f9baffe5d71c1664a46edc486de37196330798d0f1183ec25ded7085ce179299a34cb6ace7fc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
